# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Главная
    url: /
    weight: 10
  - name: Обо мне
    url: /#summary
    weight: 11
  - name: Кейсы
    url: /#cases
    weight: 12
  - name: Карьера
    url: /#timeline
    weight: 13
  - name: Media Kit
    url: /#media-kit
    weight: 14
  - name: Календарь
    url: /#events
    weight: 15
  - name: Услуги
    url: /#services
    weight: 16
  - name: Блог
    url: /#blog
    weight: 17
  - name: Награды
    url: /#recognition
    weight: 18
  - name: Контакты
    url: /#contacts
    weight: 19
  - name: Опыт
    url: experience/
    weight: 30
