# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Professional Service Provider'
    org_name: 'Алена Ирошникова - Консультант по маркетингу'
    description: 'Алена Ирошникова - маркетолог B2B с 18+ летним опытом. Эксперт по промышленному маркетингу, стратегическому планированию и выводу продуктов на рынок. Консультант для технических компаний России.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
    yandex: ''
  structured_data:
    enable: true
    person:
      name: 'Алена Ирошникова'
      job_title: 'Маркетолог B2B, консультант по промышленному маркетингу'
      company: 'Независимый консультант'
      url: 'https://iroshnikova.com'
      email: 'alena.iroshnikova@gmail.com'
      location: 'Россия'
      expertise: ['Маркетолог B2B', 'Промышленный маркетинг', 'Консультант по маркетингу', 'Стратегический маркетинг', 'Product Launch', 'Brand Strategy']

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Алена Ирошникова'


# Site footer
footer:
  copyright:
    notice: '© {year} Алена Ирошникова. Все права защищены.'
    license:
      enable: false
  poweredby:
    enable: false

# Localization
locale:
  date_format: '2 January 2006'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
